version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: brand-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
